name: GitHub Actions Build and Deploy Hexo
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: source
        lfs: true
    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm install
        npx gulp clean
        npx gulp
        npx hexo clean
        npx hexo generate
        sudo cp /usr/bin/git-lfs /usr/lib/git-core
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: source
        BRANCH: master
        FOLDER: public