name: GitHub Actions Build and Deploy Hexo
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        lfs: true
    - name: Install and BuildA 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm install
        npx gulp clean
        npx gulp
        npx hexo clean
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
    - uses: yrpang/github-actions-hexo@master
      with:
        deploykey: ${{secrets.ACCESS_TOKEN}}
        username: npmrun
        email: kk1549469775@gmail.com
